---
name: eliud_pkg_medium
description: "eliud_pkg_medium is a package to provide gui video, photo, imaging functionality\
  \ to your eliud app. More info at https://eliud.io"
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_medium
version: 1.1.5+5
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  camera: ^0.10.5+6                                                                                  # ANDROID IOS LINUX MACOS WEB WINDOWS
  chewie: ^1.7.4                                                                                     # ANDROID IOS       MACOS WEB
  crop_your_image: ^0.7.5                                                                            # ANDROID IOS LINUX MACOS WEB WINDOWS
  easy_image_viewer: ^1.2.1                                                                          # ANDROID IOS LINUX MACOS WEB WINDOWS
  file_picker: ^5.2.0+1                                                                              # ANDROID IOS LINUX MACOS WEB WINDOWS
  image_picker: ^1.0.4                                                                               # ANDROID IOS LINUX MACOS WEB WINDOWS
  percent_indicator: ^4.2.3                                                                          # ANDROID IOS LINUX MACOS WEB WINDOWS
  video_player: ^2.8.1                                                                               # ANDROID IOS LINUX MACOS WEB WINDOWS

  eliud_core:                                                                                        # ANDROID IOS             WEB
    path: ../eliud_core
  eliud_core_main:                                                                                   # ANDROID IOS             WEB
    path: ../eliud_core_main
  eliud_pkg_medium_model:                                                                            # ANDROID IOS             WEB
    path: ../eliud_pkg_medium_model

  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
  - packages/eliud_pkg_medium/assets/example_photo_1.jpg
  - packages/eliud_pkg_medium/assets/example_photo_2.jpg
platforms:
  android: null
  ios: null
  web: null
