---
name: eliud_pkg_medium
description: "eliud_pkg_medium is a package to provide gui video, photo, imaging functionality\
  \ to your eliud app. More info at https://eliud.io"
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_medium
version: 1.3.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  camera: ^0.11.0+2
  chewie: ^1.8.5
  crop_your_image: ^1.1.0
  easy_image_viewer: ^1.5.1
  file_picker: ^8.1.2
  flutter_bloc: ^8.1.6
  image_picker: ^1.1.2
  percent_indicator: ^4.2.3
  tuple: ^2.0.2
  video_player: ^2.9.1
  eliud_core: ^1.3.0
  eliud_core_main: ^1.3.0
  eliud_pkg_medium_model: ^1.3.0
  eliud_core_helpers: ^1.3.0
  eliud_core_model: ^1.3.0
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.12
  eliud_generator: ^1.1.7
  lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
  - packages/eliud_pkg_medium/assets/example_photo_1.jpg
  - packages/eliud_pkg_medium/assets/example_photo_2.jpg
platforms:
  android: null
  ios: null
  web: null
