---
name: eliud_pkg_medium
description: Eliud package for medium tools
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_medium
version: 1.0.1+18
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5
  chewie: ^1.4.0
  crop_your_image: ^0.7.4
  file_picker: ^5.2.0+1
  image_picker: ^0.8.6
  percent_indicator: ^4.2.3
  pinch_zoom: ^1.0.0
  easy_image_viewer: ^1.2.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  bloc: ^8.1.0
  cloud_firestore: ^4.6.0
  intl: ^0.18.1
  datetime_picker_formfield: ^2.0.0
  meta: ^1.8.0
  collection: ^1.17.0
  http: ^0.13.5
  video_player: ^2.6.1
  tuple: ^2.0.1
  eliud_core: ^1.0.16+13
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: 1.0.7
flutter:
  uses-material-design: true
  assets:
  - packages/eliud_pkg_medium/assets/example_photo_1.jpg
  - packages/eliud_pkg_medium/assets/example_photo_2.jpg
platforms:
  android: null
  ios: null
  web: null
