name: eliud_pkg_medium
description: Eliud package for medium tools
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: 0.9.6
  chewie: 1.3.2
  crop_your_image: 0.7.2
  image_picker_gallery_camera:
    path: ../../image_picker_gallery_camera
  file_picker: 4.5.1
  flutter_carousel_slider: 1.0.8
  flutter_staggered_grid_view: 0.6.1
  percent_indicator: 4.2.2
  pinch_zoom: 1.0.0

  eliud_core:
    path: ../eliud_core

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - packages/eliud_pkg_medium/assets/example_photo_1.jpg
    - packages/eliud_pkg_medium/assets/example_photo_2.jpg
