---
name: eliud_pkg_medium
description: "eliud_pkg_medium is a package to provide gui video, photo, imaging functionality\
  \ to your eliud app. More info at https://eliud.io"
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_medium
version: 1.1.6
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  camera: ^0.10.5+6
  chewie: ^1.7.4
  crop_your_image: ^0.7.5
  easy_image_viewer: ^1.2.1
  file_picker: ^5.2.0+1
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.4
  percent_indicator: ^4.2.3
  tuple: ^2.0.2
  video_player: ^2.8.1
  eliud_core: ^1.1.6
  eliud_core_main: ^1.0.2
  eliud_pkg_medium_model: ^1.0.0
  eliud_core_helpers: ^1.0.0
  eliud_core_model: ^1.0.0
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: ^1.1.7
  lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
  - packages/eliud_pkg_medium/assets/example_photo_1.jpg
  - packages/eliud_pkg_medium/assets/example_photo_2.jpg
platforms:
  android: null
  ios: null
  web: null
