name: eliud_pkg_medium
description: Eliud package for medium tools
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera: 0.10.5
  chewie: 1.4.0
  crop_your_image: 0.7.4
  file_picker: ^5.2.0+1
  image_picker: 0.8.6
  percent_indicator: 4.2.3
  pinch_zoom: 1.0.0
  easy_image_viewer: 1.2.0

  eliud_core:
    path: ../eliud_core

dev_dependencies:
  build_runner: "2.1.2"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - packages/eliud_pkg_medium/assets/example_photo_1.jpg
    - packages/eliud_pkg_medium/assets/example_photo_2.jpg
