name: eliud_pkg_medium
description: Eliud package for medium tools
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  percent_indicator: 3.0.1
  camera: 0.9.3+1
  image_picker_gallery_camera: 0.2.2
  file_picker: 4.2.7
  crop_your_image: 0.6.0+1
  flutter_carousel_slider: 1.0.8
  pinch_zoom: 1.0.0
  flutter_staggered_grid_view: 0.4.0
  chewie: 1.2.2

  eliud_core:
    path: ../eliud_core

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - packages/eliud_pkg_create/assets/example_photo_1.jpg
    - packages/eliud_pkg_create/assets/example_photo_2.jpg
